meta_product_name: "Small Towns LGPD"
meta_title: "Small Towns LGPD - Simplificando a implementação da LGPD para as cidades"
meta_description: "Simplificando a implementação da LGPD para as cidades"
meta_image: "home2.png" # should exist in `app/assets/images/`
